In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# creating arrays 

# 1D array
ar1 = np.array([1, 2, 3, 4, 5])
ar1

array([1, 2, 3, 4, 5])

In [ ]:
print(type(ar1))
print(ar1.shape)
print(ar1.ndim)

<class 'numpy.ndarray'>
(5,)
1


In [ ]:
# 2D array
ar2 = np.array([1, 2, 3, 4, 5])
ar2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [ ]:
ar2 = np.array([[1, 2, 3, 4,5],[5, 6, 7, 8, 9]])
ar2

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [15]:
! pip install html5lib

In [18]:
df = pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list')
df[0]

Bank Name               City          State  \
0  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania   
1                          Citizens Bank           Sac City           Iowa   
2               Heartland Tri-State Bank            Elkhart         Kansas   
3                    First Republic Bank      San Francisco     California   
4                         Signature Bank           New York       New York   
5                    Silicon Valley Bank        Santa Clara     California   
6                      Almena State Bank             Almena         Kansas   
7             First City Bank of Florida  Fort Walton Beach        Florida   
8                   The First State Bank      Barboursville  West Virginia   
9                     Ericson State Bank            Ericson       Nebraska   

    Cert                 Aquiring Institution       Closing Date   Fund  
0  27332    Fulton Bank, National Association     April 26, 2024  10546  
1   8758            Iowa Trust & Savings Bank   November 3, 2023  10545  
2  25851               Dream First Bank, N.A.      July 28, 2023  10544  
3  59017            JPMorgan Chase Bank, N.A.        May 1, 2023  10543  
4  57053                  Flagstar Bank, N.A.     March 12, 2023  10540  
5  24735  First Citizens Bank & Trust Company     March 10, 2023  10539  
6  15426                          Equity Bank   October 23, 2020  10538  
7  16748            United Fidelity Bank, fsb   October 16, 2020  10537  
8  14361                       MVB Bank, Inc.      April 3, 2020  10536  
9  18265           Farmers and Merchants Bank  February 14, 2020  10535

In [19]:
import seaborn as sns

In [ ]:
sns.load_dataset()