In [1]:
import numpy as np

In [2]:
a = np.arange(20, 100, 3)
a

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68,
       71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [3]:
b = np.random.permutation(10)
b

array([4, 9, 1, 6, 2, 7, 0, 8, 3, 5])

In [4]:
np.random.randint(20, 30)

29

In [5]:
a = np.arange(10)

In [7]:
a.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
b = np.random.rand(1, 2)
b.ndim

2