In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.shape

(10,)

In [5]:
b = np.random.randint(0, 10, (1, 10))
b

array([[2, 3, 9, 7, 7, 2, 7, 7, 1, 8]])

In [6]:
b.shape

(1, 10)

In [7]:
c = a[np.newaxis, :]
c

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
c.shape

(1, 10)

In [9]:
d = b+c
d

array([[ 2,  4, 11, 10, 11,  7, 13, 14,  9, 17]])

In [10]:
d.shape

(1, 10)

In [11]:
np.squeeze(d)

array([ 2,  4, 11, 10, 11,  7, 13, 14,  9, 17])

In [12]:
d.shape

(1, 10)

In [13]:
d

array([[ 2,  4, 11, 10, 11,  7, 13, 14,  9, 17]])

In [14]:
np.add(a, b)

array([[ 2,  4, 11, 10, 11,  7, 13, 14,  9, 17]])

In [15]:
np.sum(a)

45

In [16]:
a = np.arange(80).reshape(2, 2, 5, 4)
a

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]],


       [[[40, 41, 42, 43],
         [44, 45, 46, 47],
         [48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]],

        [[60, 61, 62, 63],
         [64, 65, 66, 67],
         [68, 69, 70, 71],
         [72, 73, 74, 75],
         [76, 77, 78, 79]]]])

In [17]:
a.ndim

4

In [18]:
a.shape

(2, 2, 5, 4)

In [19]:
a.size

80

In [20]:
a.sum()

3160

In [21]:
np.sum(a, axis = 2)

array([[[ 40,  45,  50,  55],
        [140, 145, 150, 155]],

       [[240, 245, 250, 255],
        [340, 345, 350, 355]]])

In [22]:
n = 1000000
a = np.random.rand(n)
b = np.random.rand(n)
%timeit a + b 
%timeit np.add(a, b)

8.74 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
6.31 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
np.subtract(a, b)

array([-0.2662082 ,  0.11591559, -0.60159734, ...,  0.22064805,
        0.13257367, -0.48081405])

In [24]:
a-b

array([-0.2662082 ,  0.11591559, -0.60159734, ...,  0.22064805,
        0.13257367, -0.48081405])

In [25]:
np.multiply(a, b)

array([0.0201961 , 0.3358713 , 0.39690798, ..., 0.14585544, 0.03282036,
       0.39248199])

In [26]:
a * b

array([0.0201961 , 0.3358713 , 0.39690798, ..., 0.14585544, 0.03282036,
       0.39248199])

In [27]:
np.power(a, b)

array([0.40107301, 0.79156312, 0.39772547, ..., 0.82316454, 0.84285313,
       0.46398197])

In [28]:
a ** b

array([0.40107301, 0.79156312, 0.39772547, ..., 0.82316454, 0.84285313,
       0.46398197])

In [29]:
np.divide(a, b)

array([0.18793457, 1.22101172, 0.39775846, ..., 1.76826817, 2.04699308,
       0.47246436])

In [30]:
a / b

array([0.18793457, 1.22101172, 0.39775846, ..., 1.76826817, 2.04699308,
       0.47246436])

In [31]:
a % b

array([0.061608  , 0.11591559, 0.39733299, ..., 0.22064805, 0.00595042,
       0.4306202 ])

In [32]:
np.divmod(a, b)

(array([0., 1., 0., ..., 1., 2., 0.]),
 array([0.061608  , 0.11591559, 0.39733299, ..., 0.22064805, 0.00595042,
        0.4306202 ]))

In [33]:
np.mod(a, b)

array([0.061608  , 0.11591559, 0.39733299, ..., 0.22064805, 0.00595042,
       0.4306202 ])

In [34]:
a.mean()

0.4998243338378508

In [35]:
a.mean(axis = 0)

0.4998243338378508

In [36]:
a.std()

0.2885733591575582

In [37]:
a.var()

0.08327458361547709

In [38]:
np.sin(a)

array([0.06156903, 0.59751037, 0.38696048, ..., 0.48629964, 0.25630439,
       0.41743446])

In [39]:
np.cos(a)

array([0.99810283, 0.80186118, 0.9220963 , ..., 0.87379211, 0.96659612,
       0.90870703])

In [40]:
np.arcsin(a)

array([0.06164704, 0.69500944, 0.40860875, ..., 0.53268704, 0.26219063,
       0.44517984])

In [41]:
a == b

array([False, False, False, ..., False, False, False])

In [42]:
a != b

array([ True,  True,  True, ...,  True,  True,  True])

In [43]:
a > b

array([False,  True, False, ...,  True,  True, False])

In [44]:
a < b

array([ True, False,  True, ..., False, False,  True])

In [45]:
(a > b) & (a < b)

array([False, False, False, ..., False, False, False])

In [46]:
a = np.random.rand(5)
a[3] = np.nan
a

array([0.17125778, 0.50046044, 0.83991857,        nan, 0.19169052])

In [47]:
a.sum()

nan

In [48]:
np.nansum(a)

1.7033273142041865

In [49]:
np.floor(a)

array([ 0.,  0.,  0., nan,  0.])

In [50]:
np.ceil(a)

array([ 1.,  1.,  1., nan,  1.])

In [51]:
np.trunc(a)

array([ 0.,  0.,  0., nan,  0.])

In [52]:
myArray1 = np.random.rand(50) * 10
myArray1

array([8.64860853, 8.62311464, 5.91834125, 5.95107591, 1.9497835 ,
       5.27270965, 0.84952475, 1.72497523, 1.99178399, 7.11994158,
       4.71676006, 3.64213815, 7.63624901, 9.66900629, 2.65847938,
       4.87111324, 7.30788507, 5.16663429, 0.64826024, 0.55485667,
       2.56008676, 9.16076827, 1.22661195, 6.61196389, 6.50129287,
       1.54717465, 9.13672563, 9.78306129, 4.12601451, 2.58335246,
       7.53215279, 6.06662517, 7.71206485, 2.3945096 , 7.54964332,
       1.61670916, 9.07671321, 4.28142953, 4.19058478, 7.61377514,
       9.22580534, 0.29385127, 1.63842484, 4.93561682, 7.07517105,
       6.17773385, 4.77599443, 0.69163264, 5.09149763, 4.63554639])

In [65]:
# remove decimal point values
myArray1 = np.floor(myArray1)
myArray1

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 3.,
       4., 4., 4., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5., 6., 6., 6., 6.,
       7., 7., 7., 7., 7., 7., 7., 7., 8., 8., 9., 9., 9., 9., 9., 9.])

In [66]:
myArray2 = myArray1[myArray1 > 5]
myArray2

array([6., 6., 6., 6., 7., 7., 7., 7., 7., 7., 7., 7., 8., 8., 9., 9., 9.,
       9., 9., 9.])

In [67]:
myArray1 = np.sort(myArray1)
myArray1

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 3.,
       4., 4., 4., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5., 6., 6., 6., 6.,
       7., 7., 7., 7., 7., 7., 7., 7., 8., 8., 9., 9., 9., 9., 9., 9.])

In [68]:
myArray2 = myArray2[::-1]
myArray2

array([9., 9., 9., 9., 9., 9., 8., 8., 7., 7., 7., 7., 7., 7., 7., 7., 6.,
       6., 6., 6.])

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [71]:
np.empty(5)

array([1., 1., 1., 1., 1.])